version: "2.2"

services:
  elastic:
    image: elasticsearch:8.3.3
    networks:
      - shared
    volumes:
      - certs:/usr/share/elasticsearch/config/certs
      - esdata01:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - 9200:9200
    environment:
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
      - ELASTIC_PASSWORD=elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl http://localhost:9200 | grep -q 'You Know, for Search'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  kibana:
    depends_on:
      elastic:
        condition: service_healthy
    image: kibana:8.3.3
    networks:
      - shared
    volumes:
      - certs:/usr/share/kibana/config/certs
      - kibanadata:/usr/share/kibana/data
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    environment:
      - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    healthcheck:
      test:
        [
            "CMD-SHELL",
            "curl http://localhost:5601/api/status | grep -q '401'",
        ]
      interval: 10s
      timeout: 10s
      retries: 120

  apm-server:
    image: elastic/apm-server:8.3.3
    networks:
      - shared
    volumes:
      - certs:/usr/share/apm-server/config/certs
      - ./apm-server.yml:/usr/share/apm-server/apm-server.yml
    depends_on:
      elastic:
        condition: service_healthy
      kibana:
        condition: service_healthy
    cap_add: ["ALL"]
    ports:
      - 8200:8200
    command: --strict.perms=false
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:8200/

  collector:
    networks:
      - shared
    depends_on:
      - apm-server
    image: otel/opentelemetry-collector:0.58.0
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./collector/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" #otlp-grpc exporter

volumes:
  certs:
    driver: local
  esdata01:
    driver: local
  kibanadata:
    driver: local

networks:
  shared:
    driver: bridge